fixtures:
  forge_modules:
    logrotate: 'yo61-logrotate'
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "2.2.2"
  symlinks:
    mongodb: "#{source_dir}"
